[build]
command = "npm run build"
output_directory = ".next"

[build.environment]
NODE_VERSION = "18"

[site]
bucket = "./.next"
entry-point = "./.cloudflare/workers-site"

[env.production]
name = "production"
route = "*"
